export const PRODUCTS = [
    {
      id: 1,
      title: "Aircraft Carrier",
      img: "aircraft-carrier",
      price: 30000,
      sale: true,
      salePercent: 2,
      categories: ["Boat"],
    },
    {
      id: 2,
      title: "Boat",
      img: "boat",
      price: 700,
      sale: false,
      categories: ["Boat"],
    },
    {
      id: 3,
      title: "Bus",
      img: "bus",
      price: 300,
      sale: true,
      salePercent: 10,
      categories: ["Bus"],
    },
    {
      id: 4,
      title: "Cabriolet",
      img: "cabriolet",
      price: 900,
      sale: true,
      salePercent: 25,
      categories: ["Car"],
    },
    {
      id: 5,
      title: "Commercial Plane",
      img: "commercial-plane",
      price: 1000,
      sale: false,
      categories: ["Aircraft"],
    },
    {
      id: 6,
      title: "Electric car",
      img: "electric-car",
      price: 3000,
      sale: false,
      categories: ["Car"],
    },
    {
      id: 7,
      title: "Helicopter police",
      img: "helicopter-police",
      price: 1000,
      sale: true,
      salePercent: 15,
      categories: ["Aircraft", "Helicopter"],
    },
    {
      id: 8,
      title: "Helicopter",
      img: "helicopter",
      price: 900,
      sale: true,
      salePercent: 35,
      categories: ["Aircraft", "Helicopter"],
    },
    {
      id: 9,
      title: "Minibus",
      img: "minibus",
      price: 700,
      sale: true,
      salePercent: 5,
      categories: ["Car", "Bus"],
    },
    {
      id: 10,
      title: "Motorbike",
      img: "motorbike",
      price: 200,
      sale: true,
      salePercent: 25,
      categories: ["Bike"],
    },
    {
      id: 11,
      title: "Off Road",
      img: "off-road",
      price: 600,
      sale: false,
      categories: ["Car"],
    },
    {
      id: 12,
      title: "Police Car",
      img: "police-car",
      price: 100,
      sale: false,
      categories: ["Car"],
    },
    {
      id: 13,
      title: "School Bus",
      img: "school-bus",
      price: 150,
      sale: true,
      salePercent: 8,
      categories: ["Bus"],
    },
    {
      id: 14,
      title: "Scooter",
      img: "scooter",
      price: 80,
      sale: true,
      salePercent: 13,
      categories: ["Bike"],
    },
    {
      id: 15,
      title: "Small Plane",
      img: "small-plane",
      price: 3000,
      sale: false,
      categories: ["Aircraft"],
    },
    {
      id: 16,
      title: "Speed Boat",
      img: "speed-boat",
      price: 2000,
      sale: true,
      salePercent: 34,
      categories: ["Boat"],
    },
    {
      id: 17,
      title: "Sport Car",
      img: "sport-car",
      price: 10000,
      sale: true,
      salePercent: 3,
      categories: ["Car"],
    },
    {
      id: 18,
      title: "Suv",
      img: "Suv",
      price: 300,
      sale: true,
      salePercent: 13,
      categories: ["Car", "Bus"],
    },
  ];
  export const USERS = [
    //   {
    // //     name: "Ivan",
    // //     email: "ivan@gmail.com",
    // //     password: "123",
    // //     favourites: [9, 18, 7],
    // //     orders: [
    // //       { id: 2, count: 2 },
    // //       { id: 16, count: 4 },
    // //       { id: 3, count: 1 },
    // //     ],
    // //     shoppingCart: [
    // //       { id: 9, count: 1 },
    // //       { id: 3, count: 1 },
    // //     ],
    // //     status: false,
    // //   },
  ];
  